#!/usr/bin/env python3
"""
Bayesian / bandit-style agent for the Blackbox Tournament.

Strategy:
- Maintains a simple belief about which inputs matter.
- Runs experiments tracking mean power_output per variable band.
- Writes markdown reports summarizing findings.
- Buys cheap reports from others to read their markdown.
"""

import json
import os
import time
import random

SHARED_DIR = os.environ.get("BLACKBOX_SHARED_DIR")
if not SHARED_DIR:
    SHARED_DIR = os.path.join(os.path.dirname(__file__), "..", "shared")

JOBS_PATH = os.path.join(SHARED_DIR, "jobs.jsonl")
STATE_PATH = os.path.join(SHARED_DIR, "state.json")
RESULTS_PATH = os.path.join(SHARED_DIR, "results.jsonl")
MARKET_DIR = os.path.join(SHARED_DIR, "market")
LISTINGS_PATH = os.path.join(MARKET_DIR, "listings.jsonl")
OWNERSHIP_DIR = os.path.join(SHARED_DIR, "ownership")

PLAYER_NAME = os.environ.get("BLACKBOX_PLAYER_NAME", "bayesian_agent")

INPUT_VARS = ["P", "T", "F", "VA", "VB", "VC", "tau", "L", "C"]


def read_state():
    if not os.path.exists(STATE_PATH):
        return {}
    with open(STATE_PATH, "r") as f:
        return json.load(f)


def read_results_all():
    if not os.path.exists(RESULTS_PATH):
        return []
    lines = []
    with open(RESULTS_PATH, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                lines.append(json.loads(line))
    return lines


def read_listings():
    if not os.path.exists(LISTINGS_PATH):
        return []
    items = []
    with open(LISTINGS_PATH, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                items.append(json.loads(line))
    return items


def read_owned_reports():
    own_path = os.path.join(OWNERSHIP_DIR, f"{PLAYER_NAME}.json")
    if not os.path.exists(own_path):
        return []
    with open(own_path, "r") as f:
        return json.load(f)


def submit_job(job: dict):
    with open(JOBS_PATH, "a") as f:
        f.write(json.dumps(job) + "\n")


def run_experiment(inputs: dict):
    submit_job({"type": "run", "player": PLAYER_NAME, "inputs": inputs})


def create_markdown_report(report_id: int, belief: dict, experiments: list):
    """
    Build a markdown report from the current belief model and experiment history.
    """
    body = f"""# Bayesian Analysis Report by {PLAYER_NAME}

## Variable Belief Summary

| Variable | High Mean | Low Mean | Strength |
|----------|-----------|----------|----------|
"""
    for var in INPUT_VARS:
        b = belief.get(var, {})
        hm = b.get("high_mean", "N/A")
        lm = b.get("low_mean", "N/A")
        diff = abs(hm - lm) if isinstance(hm, (int, float)) and isinstance(lm, (int, float)) else 0
        strength = "strong" if diff > 0.1 else "weak"
        body += f"| {var} | {hm if hm != 'N/A' else '—'} | {lm if lm != 'N/A' else '—'} | {strength} |\n"

    body += f"""
## Best Setting Found So Far

"""
    best = {}
    for var in INPUT_VARS:
        b = belief.get(var, {})
        hm = b.get("high_mean", 0.5)
        lm = b.get("low_mean", 0.5)
        best[var] = 0.8 if hm > lm else 0.2
    body += f"```json\n{json.dumps(best, indent=2)}\n```\n"

    body += f"""
## Experiment Log Sample

| P | T | F | Power | Vibration |
|---|---|---|-------|-----------|
"""
    for r in experiments[:15]:
        inp = r.get("inputs", {})
        out = r.get("outputs", {})
        body += f"| {inp.get('P','')} | {inp.get('T','')} | {inp.get('F','')} | {out.get('power_output','')} | {out.get('vibration','')} |\n"

    body += f"""
## Read Reports

<!-- Cite report IDs you bought and learned from -->

_Auto-generated by {PLAYER_NAME}_
"""

    submit_job({
        "type": "create_report",
        "player": PLAYER_NAME,
        "report": {
            "id": report_id,
            "creator": PLAYER_NAME,
            "timestamp": time.time(),
            "price": 3.0,
            "cited_reports": [],
            "body": body,
        },
    })


def list_report(report_id: int, price: float):
    submit_job({"type": "list_report", "player": PLAYER_NAME, "report_id": report_id, "price": price})


def buy_report(report_id: int):
    submit_job({"type": "buy_report", "player": PLAYER_NAME, "report_id": report_id})


# ---------------------------------------------------------------------------
# BELIEF / BANDIT LOGIC
# ---------------------------------------------------------------------------

def bandit_inputs(belief: dict) -> dict:
    inputs = {}
    for var in INPUT_VARS:
        b = belief.get(var, {"high_mean": 0.5, "low_mean": 0.5})
        diff = b.get("high_mean", 0.5) - b.get("low_mean", 0.5)
        if diff > 0.05:
            inputs[var] = round(random.uniform(0.6, 1.0), 2)
        elif diff < -0.05:
            inputs[var] = round(random.uniform(0.0, 0.4), 2)
        else:
            inputs[var] = round(random.random(), 2)
    return inputs


def update_belief(belief: dict, inputs: dict, outputs: dict):
    power = outputs.get("power_output", 0.0)
    for var in INPUT_VARS:
        val = inputs[var]
        b = belief.setdefault(var, {"high_sum": 0.0, "high_n": 0, "low_sum": 0.0, "low_n": 0})
        if val >= 0.5:
            b["high_sum"] += power
            b["high_n"] += 1
            b["high_mean"] = b["high_sum"] / b["high_n"]
        else:
            b["low_sum"] += power
            b["low_n"] += 1
            b["low_mean"] = b["low_sum"] / b["low_n"]


# ---------------------------------------------------------------------------
# STRATEGY
# ---------------------------------------------------------------------------

def decide_action(state, results, listings, owned, belief: dict, experiments: list):
    my_state = state.get("players", {}).get(PLAYER_NAME, {})
    energy = my_state.get("energy", 100.0)

    # 1. BUY cheap reports
    for listing in listings:
        if not listing.get("active"):
            continue
        rid = listing["report_id"]
        price = listing.get("price", 999)
        if rid not in owned and price <= 5.0 and energy >= price + 5.0:
            buy_report(rid)
            print(f"[{PLAYER_NAME}] Attempted to buy report {rid} for {price} energy.")
            return

    # 2. RUN experiment
    if energy >= 2.0:
        inputs = bandit_inputs(belief)
        run_experiment(inputs)
        print(f"[{PLAYER_NAME}] Submitted experiment.")
        return

    # 3. CREATE + LIST report
    if energy >= 5.0 and len(experiments) >= 5:
        report_id = hash(f"{PLAYER_NAME}_{int(time.time())}") % 1000000
        create_markdown_report(report_id, belief, experiments)
        list_report(report_id, price=3.0)
        print(f"[{PLAYER_NAME}] Created and listed report {report_id}.")
        return

    print(f"[{PLAYER_NAME}] Idle (energy={energy:.1f}).")


def main():
    print(f"[{PLAYER_NAME}] Bayesian agent started.")
    belief = {}
    experiments = []
    while True:
        state = read_state()
        results = read_results_all()
        listings = read_listings()
        owned = read_owned_reports()

        for r in results:
            if r.get("type") == "run" and r.get("ok") and r.get("player") == PLAYER_NAME:
                update_belief(belief, r["inputs"], r["outputs"])
                experiments.append(r)

        decide_action(state, results, listings, owned, belief, experiments)
        time.sleep(3.0)


if __name__ == "__main__":
    main()
