#!/usr/bin/env python3
"""
Random agent: submits random experiments and occasionally creates reports.
"""

import json
import os
import time
import random

# Allow an agent workspace anywhere on disk by pointing to the tournament shared folder.
SHARED_DIR = os.environ.get("BLACKBOX_SHARED_DIR")
if not SHARED_DIR:
    SHARED_DIR = os.path.join(os.path.dirname(__file__), "..", "shared")

JOBS_PATH = os.path.join(SHARED_DIR, "jobs.jsonl")
STATE_PATH = os.path.join(SHARED_DIR, "state.json")
OWNERSHIP_DIR = os.path.join(SHARED_DIR, "ownership")

PLAYER_NAME = os.environ.get("BLACKBOX_PLAYER_NAME", "random_agent")


def read_state():
    if not os.path.exists(STATE_PATH):
        return {}
    with open(STATE_PATH, "r") as f:
        return json.load(f)


def submit_job(job: dict):
    with open(JOBS_PATH, "a") as f:
        f.write(json.dumps(job) + "\n")


def random_inputs():
    return {
        "P": round(random.random(), 2),
        "T": round(random.random(), 2),
        "F": round(random.random(), 2),
        "VA": round(random.random(), 2),
        "VB": round(random.random(), 2),
        "VC": round(random.random(), 2),
        "tau": round(random.random(), 2),
        "L": round(random.random(), 2),
        "C": round(random.random(), 2),
    }


def run_experiment(inputs: dict):
    submit_job({
        "type": "run",
        "player": PLAYER_NAME,
        "inputs": inputs,
    })


def create_report(report_id: int, experiment_results: list):
    """
    Generate a markdown report with observations and citations.
    """
    body = f"""# Exploration Report by {PLAYER_NAME}

## Experiment Log

| P | T | F | VA | VB | VC | tau | L | C | Power | Vibration | Efficiency | Heat Loss |
|---|---|---|---|---|---|---|---|---|-------|-----------|------------|-----------|
"""
    for r in experiment_results:
        inp = r.get("inputs", {})
        out = r.get("outputs", {})
        body += f"| {inp.get('P','')} | {inp.get('T','')} | {inp.get('F','')} | {inp.get('VA','')} | {inp.get('VB','')} | {inp.get('VC','')} | {inp.get('tau','')} | {inp.get('L','')} | {inp.get('C','')} | {out.get('power_output','')} | {out.get('vibration','')} | {out.get('efficiency','')} | {out.get('heat_loss','')} |\n"

    body += f"""
## Observations

Based on {len(experiment_results)} random experiments, no clear causal pattern has emerged yet.
Pressure (P) and Temperature (T) appear to influence power output.
Further experiments are needed.

## Citations

<!-- If you buy reports, cite their IDs here -->

_Auto-generated by {PLAYER_NAME}_
"""

    submit_job({
        "type": "create_report",
        "player": PLAYER_NAME,
        "report": {
            "id": report_id,
            "creator": PLAYER_NAME,
            "timestamp": time.time(),
            "price": 2.0,
            "cited_reports": [],
            "body": body,
        },
    })


def main():
    print(f"[{PLAYER_NAME}] Agent started.")
    tick = 0
    experiments = []
    while True:
        state = read_state()
        my_state = state.get("players", {}).get(PLAYER_NAME, {})
        energy = my_state.get("energy", 100.0)

        if energy >= 1.0:
            inputs = random_inputs()
            run_experiment(inputs)
            experiments.append({"inputs": inputs, "outputs": {}})
            print(f"[{PLAYER_NAME}] Submitted random experiment.")

        if tick % 15 == 0 and tick > 0 and energy >= 5.0 and len(experiments) >= 3:
            # Create a report summarizing recent experiments
            report_id = random.randint(1000, 9999)
            create_report(report_id, experiments)
            experiments = []
            print(f"[{PLAYER_NAME}] Submitted report creation.")

        tick += 1
        time.sleep(2.0)


if __name__ == "__main__":
    main()
